### ISSUE TITLE
Singularity libseccomp Issue

### ISSUE THREAD

**Issue by tonideleo** [singularityware/singularity#6298]
During the sudo make I get the following error:
```
GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
# github.com/seccomp/libseccomp-golang
/root/go/pkg/mod/github.com/seccomp/libseccomp-golang@v0.9.1/seccomp_internal.go:24:2: error: #error Minimum supported version of Libseccomp is v2.2.0
   24 | #error Minimum supported version of Libseccomp is v2.2.0
      |  ^~~~~
make: *** [Makefile:183: singularity] Error 2
```

I have tried pretty much everything and uninstalled and reinstalled everything multiple times.

### What OS/distro are you running

```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


```

### How did you install Singularity

Followed the INSTALL.md guide

**Comment by DrDaveD** [comment]
Do you mean you followed the instructions from INSTALL.md?  It doesn't have a `sudo make`.  There is a `sudo make install`, is that what you mean?  It is expected that you will run the make as non-root, then make install as root.  Judging by the path beginning `/root/go` I am guessing that you did run the make as root.  That could be part of the problem.

I tried doing a build in an ubuntu:20.04 docker container and had no problems (other than slight typos in the procedure fixed in #6301).  It has a slightly older 20.04 than you have, 20.04.2, but still it has a plenty new libseccomp:
```
$ apt-cache policy libseccomp2
libseccomp2:
  Installed: 2.5.1-1ubuntu1~20.04.1
  Candidate: 2.5.1-1ubuntu1~20.04.1
  Version table:
 *** 2.5.1-1ubuntu1~20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.3-1ubuntu3.20.04.3 500
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     2.4.3-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

What version of libseccomp2 do you have?

**Comment by tonideleo** [comment]
Dear @DrDaveD, thank you for your reply!
When I run the "apt-cache policy libseccomp2" I get exactly the same output. I just tried again installing Singularity (v3.8.3) by deleting the go folder and re-perform everything from the beginning. 

The only step I was not able to follow from the INSTALL.md was the golangci-lint, as I get the following error and I needed to use sudo to make it work:
```
 curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.0
golangci/golangci-lint info checking GitHub for tag 'v1.42.0'
golangci/golangci-lint info found version: 1.42.0 for v1.42.0/linux/amd64
install: cannot create directory ‘/usr/local/go/work’: Permission denied
```
Then I continued with the instructions and when I try to use make (without sudo) I get the following output:
```
$ make
 GEN GO DEP /home/adeleo/singularity/builddir/starter.d
go: could not create module cache: mkdir /usr/local/go/work/pkg: permission denied
 GEN GO DEP /home/adeleo/singularity/builddir/singularity.d
go: could not create module cache: mkdir /usr/local/go/work/pkg: permission denied
 GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
go: could not create module cache: mkdir /usr/local/go/work/pkg: permission denied
make: *** [Makefile:183: singularity] Error 1
```
Which prompted me in the previous attempt to use sudo. Is this something you have seen before? I am very puzzled I was not able to make it work!

Again, thanks so much for your help!

**Comment by DrDaveD** [comment]
That looks like you may have GOPATH set to /usr/local/go, or some other GO-related environment variable.  Start from scratch from the instructions in INSTALL.md as an ordinary user.

**Comment by tonideleo** [comment]
Unfortunately I wasn't able to make libseccomp be properly found during the make with the new Ubuntu 20.04 in any other way.
Following #6236 I used:
```
./mconfig --without-seccomp
```
and successfully installed singularity.
Thanks @DrDaveD for checking in!
